name: Run tests on Pull Request

on: [push, workflow_dispatch]

jobs:
  run-command:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: run tests
        run: |
          echo "Pull Request triggered!"
          echo "Running tests..."
          vitest --passWithNoTest  
